### ISSUE TITLE
Unrecognized Put Route

### ISSUE THREAD

**Issue by CaptainM** [CaptainM/workout_journal#24]
@harimohanraj89 @htella @DrRobotmck 

When a user clicks a 'Workout Completed' button, I would like for that workout to be saved in the User/Workout join table, so that the user never has to do the same workout twice.  

This is my new route: 
    put '/user_completed_workout/:workout_id', to: 'exercises#user_completed_workout'

And I put the path in my Exercise controller: 
    def user_completed_workout
		user = User.find(params[:current_user_id])
		workout = Workout.find(params[:workout_id])
		user.workouts << workout
	end

Lastly, I added the event handler and ajax put request: 
    $(function() {
	$("#exercises").on("mouseenter", ".exercise-name", showDetails);
	$("#exercises").on("mouseleave", ".exercise-name", hideDetails);
	$("#exercises").on("click",'button#button', getVideos);
	$("#exercises").on("click", 'button#secondButton', workoutCompleted);
});

function workoutCompleted() {
	console.log($(this).data("id"));
	$.ajax({
		url: '/user_completed_workout/' + $(this).data("id"),
		type: 'put'
	})
		.done();//do I need anything here? What I want it to do is in the controller);
    };

But when I run this, my error says " PUT http://localhost:3000/user_completed_workout/2 404 (Not Found)".  It's building the exact URL that I intended it to, but that put request cannot be found.  I know that this route isn't restful, is that a part of the problem?  Is there something else I should be looking into?  I've played with this for a while and Googled it but didn't find much to go on.  It seems that this is the way that Hoots app was written. 

On another note, once I figure out what is wrong with my route, I'm wondering where I should be saving the workout/user affiliation in the join table.  Does it belong as a function after the .done() in the javascript file, or does it belong in the controller as I have above?

**Comment by harimohanraj89** [comment]
To address the "other note" first, you are correct in performing those actions in the controller.

As for this missing route, I am actually unsure. Have you run `rake routes` in your terminal to double check that the routes you have set up through your `routes.rb` file are indeed correct? Is there a branch on your repository that we can look at to see this state of your codebase?

**Comment by CaptainM** [comment]
Hi Hari, 

Yes, I verified that the route is in the rake routes.  When I check rake routes I see the below:
PUT    /user_completed_workout/:workout_id(.:format) exercises#user_completed_workout

I've merged everything into master so it should be there.  The relevant places to look for the code are in: routes, exercise_controller, application.js, and the workout model (because I wasn't sure if I was supposed to be putting the below code in the workout model or in the controller.  Based on what you said in your comment for a separate issue, I believe I need to keep the below code in the workout model as opposed to the exercise controller.). 

    	# def self.user_completed_workout(user)
	# 	self.users.push(user)
	# end
