### ISSUE TITLE
Testing Ajax with Jasmine

### ISSUE THREAD

**Issue by CaptainM** [CaptainM/workout_journal#25]
@harimohanraj89 @htella @DrRobotmck 
While I'm submitting one million questions, can you let me know if we're expected to use https://github.com/jasmine/jasmine-ajax to test an ajax request like the below? I'd like to know if I'm heading in the right direction before I deep dive into it. 

        function fetchAndRenderExercises() {
	    $.get("/exercises").done(function(data) {
		data.forEach(renderExercise);
	});
    }
I submitted the question the the class yesterday but didn't hear back to see what other people are doing.  Pretty much everything in my JS involves Ajax and I've run into difficulty testing it. 

Thank you!!

**Comment by harimohanraj89** [comment]
Testing Ajax calls is a little more involved than the usual **unit tests** that we have been performing so far in class. That being said, I would focus your testing efforts to dive deeper into your rspec tests. Here are some things to do.

* Shoulda matchers allow you test associations between models. For example, you can test whether a workout has many exercises. You should write association tests.
* Refactor your controllers to move as much logic as possible into your methods on your model class (for eg. how are you fetching a random workout right now? where does the logic for a user completing a workout currently live?) Once you have moved this logic into your models, these methods are now testable.
